// Copyright 2026 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::collections::BTreeMap;
use std::collections::BTreeSet;

use crate::cli_util::CommandHelper;
use crate::command_error::CommandError;
use crate::command_error::user_error_with_message;
use crate::commands::cr::CrLogArgs;
use crate::commands::cr::review::CodeReviewTemplateLanguageExtension;
use crate::commands::cr::util::log_commits;
use crate::commands::forgejo::client::ForgejoClient;
use crate::commands::log;
use crate::ui::Ui;
use jj_lib::ref_name::RemoteName;

pub async fn cmd_forgejo_log(
    ui: &mut Ui,
    command: &CommandHelper,
    remote_name: &RemoteName,
    _args: &CrLogArgs,
) -> Result<(), CommandError> {
    let workspace_command = command.workspace_helper(ui).await?;
    let push_bookmark_template_text = workspace_command
        .settings()
        .get_string("templates.git_push_bookmark")?;
    let push_bookmark_template =
        workspace_command.parse_commit_template(ui, &push_bookmark_template_text)?;

    // Phase 1: Find CR IDs for all changes in the log.
    let branches_by_commit = log_commits(ui, &workspace_command)
        .await?
        .into_iter()
        .map(|commit| {
            let branch_name = String::from_utf8(push_bookmark_template.format_plain_text(&commit))
                .map_err(|err| {
                    user_error_with_message(
                        "Invalid character in bookmark name generated by templates.git_push_bookmark",
                        err.utf8_error(),
                    )
                })?;
            if branch_name.is_empty() {
                return Err(crate::command_error::user_error(
                    "Empty bookmark name generated by templates.git_push_bookmark",
                ));
            }
            Ok((commit.id().clone(), branch_name))
        })
        .collect::<Result<BTreeMap<_, _>, CommandError>>()?;

    // Phase 2: Find CR status for each CR ID.
    //
    // Forgejo has no way to query several branches at once, so this is one
    // request (plus a couple of follow-ups) per branch.
    let review_by_branch = if branches_by_commit.is_empty() {
        BTreeMap::new()
    } else {
        let client = ForgejoClient::new(ui, command, remote_name.as_str()).await?;
        let unique_branches = branches_by_commit.values().collect::<BTreeSet<_>>();
        let mut review_by_branch = BTreeMap::new();
        for branch in unique_branches {
            if let Some(pr) = client.open_pull_request_by_head(branch)? {
                review_by_branch.insert(branch.clone(), client.fetch_cr(&pr)?);
            }
        }
        review_by_branch
    };

    // Phase 3: Run `jj log` with a custom extension for making review
    // data available to the renderer
    let extension = CodeReviewTemplateLanguageExtension::new(branches_by_commit, review_by_branch);
    log::cmd_log_with_template_extensions(ui, command, &Default::default(), &[&extension]).await
}
