// Copyright 2026 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use futures::TryStreamExt as _;
use serde_json::Value;
use serde_json::json;
use std::collections::HashMap;

use crate::cli_util::CommandHelper;
use crate::cli_util::RevisionArg;
use crate::cli_util::WorkspaceCommandHelper;
use crate::command_error::CommandError;
use crate::command_error::user_error;
use crate::command_error::user_error_with_message;
use crate::commands::cr::CrUploadArgs;
use crate::commands::forgejo::client::ForgejoClient;
use crate::commands::forgejo::client::is_wip_title;
use crate::commands::forgejo::client::wip_title;
use crate::commands::git::cmd_git_push_changes;
use crate::ui::Ui;
use jj_lib::backend::CommitId;
use jj_lib::commit::Commit;
use jj_lib::object_id::ObjectId as _;
use jj_lib::ref_name::RemoteName;
use jj_lib::repo::Repo as _;

pub async fn cmd_forgejo_upload(
    ui: &mut Ui,
    command: &CommandHelper,
    remote_name: &RemoteName,
    args: &CrUploadArgs,
) -> Result<(), CommandError> {
    let client = ForgejoClient::new(ui, command, remote_name.as_str()).await?;
    let workspace_command = command.workspace_helper(ui).await?;

    let selected_revset = args.revision.clone();
    let commit_ids: Vec<CommitId> = workspace_command
        .resolve_some_revsets(ui, &[RevisionArg::from(selected_revset)])
        .await?
        .into_iter()
        .rev()
        .collect();
    workspace_command.check_rewritable(&commit_ids).await?;

    let push_bookmark_template_text = workspace_command
        .settings()
        .get_string("templates.git_push_bookmark")?;
    let push_bookmark_template =
        workspace_command.parse_commit_template(ui, &push_bookmark_template_text)?;

    let commits: Vec<Commit> = {
        let mut out = Vec::with_capacity(commit_ids.len());
        for id in &commit_ids {
            out.push(
                workspace_command
                    .repo()
                    .store()
                    .get_commit_async(id)
                    .await?,
            );
        }
        out
    };

    let mut commit_to_push_bookmark: HashMap<CommitId, String> = HashMap::new();
    for commit in &commits {
        let push_bookmark = String::from_utf8(push_bookmark_template.format_plain_text(commit))
            .map_err(|err| {
                user_error_with_message(
                    "Invalid character in bookmark name generated by templates.git_push_bookmark",
                    err.utf8_error(),
                )
            })?;
        if push_bookmark.is_empty() {
            return Err(user_error(
                "Empty bookmark name generated by templates.git_push_bookmark",
            ));
        }
        commit_to_push_bookmark.insert(commit.id().clone(), push_bookmark);
    }

    // Create/update push bookmarks and push all selected changes.
    let change_revisions = commits
        .iter()
        .map(|commit| RevisionArg::from(commit.id().hex().clone()))
        .collect();
    cmd_git_push_changes(ui, command, remote_name, change_revisions).await?;

    for commit in &commits {
        let head_ref_name = commit_to_push_bookmark
            .get(commit.id())
            .expect("bookmark mapped for every selected commit");
        let base_ref_name = compute_base_ref_name(
            ui,
            &workspace_command,
            &commit_to_push_bookmark,
            commit,
            &client.default_merge_target,
        )
        .await?;

        match client.open_pull_request_by_head(head_ref_name)? {
            Some(existing_pr) => update_pr(
                &client,
                commit,
                &parse_existing_pr(&existing_pr)?,
                &base_ref_name,
                args.message.as_deref(),
            )?,
            None => create_pr(&client, commit, head_ref_name, &base_ref_name, args.draft)?,
        }
    }

    Ok(())
}

#[derive(Clone, Debug)]
struct ExistingPr {
    number: i64,
    title: String,
    body: String,
    base_ref_name: String,
    draft: bool,
}

async fn compute_base_ref_name(
    ui: &Ui,
    workspace_command: &WorkspaceCommandHelper,
    commit_to_push_bookmark: &HashMap<CommitId, String>,
    commit: &Commit,
    default_merge_target: &str,
) -> Result<String, CommandError> {
    let Some(first_parent_id) = commit.parent_ids().first() else {
        return Ok(default_merge_target.to_string());
    };
    if is_immutable_commit(ui, workspace_command, first_parent_id).await? {
        Ok(default_merge_target.to_string())
    } else if let Some(push_bookmark) = commit_to_push_bookmark.get(first_parent_id) {
        Ok(push_bookmark.clone())
    } else {
        let parent_commit = workspace_command
            .repo()
            .store()
            .get_commit_async(first_parent_id)
            .await?;
        let template_text = workspace_command
            .settings()
            .get_string("templates.git_push_bookmark")?;
        let template = workspace_command.parse_commit_template(ui, &template_text)?;
        let push_bookmark =
            String::from_utf8(template.format_plain_text(&parent_commit)).map_err(|err| {
                user_error_with_message(
                    "Invalid character in bookmark name generated by templates.git_push_bookmark",
                    err.utf8_error(),
                )
            })?;
        if push_bookmark.is_empty() {
            return Err(user_error(
                "Empty bookmark name generated by templates.git_push_bookmark",
            ));
        }
        Ok(push_bookmark)
    }
}

async fn is_immutable_commit(
    ui: &Ui,
    workspace_command: &WorkspaceCommandHelper,
    commit_id: &CommitId,
) -> Result<bool, CommandError> {
    let expr = workspace_command.parse_revset(
        ui,
        &RevisionArg::from(format!("{} & immutable()", commit_id.hex())),
    )?;
    let mut stream = expr.evaluate_to_commit_ids()?;
    Ok(stream.try_next().await?.is_some())
}

fn parse_existing_pr(pr: &Value) -> Result<ExistingPr, CommandError> {
    let number = pr["number"]
        .as_i64()
        .ok_or_else(|| user_error("Forgejo pull request is missing 'number'"))?;
    let title = pr["title"].as_str().unwrap_or_default().to_string();

    Ok(ExistingPr {
        number,
        draft: pr["draft"].as_bool().unwrap_or(false) || is_wip_title(&title),
        title,
        body: pr["body"].as_str().unwrap_or_default().to_string(),
        base_ref_name: pr["base"]["ref"].as_str().unwrap_or_default().to_string(),
    })
}

fn create_pr(
    client: &ForgejoClient,
    commit: &Commit,
    head_ref_name: &str,
    base_ref_name: &str,
    draft: bool,
) -> Result<(), CommandError> {
    let (title, body) = split_title_body(commit.description());
    // Forgejo has no API flag for drafts; a "WIP:" title prefix is what marks
    // a pull request as one.
    let title = if draft { wip_title(&title) } else { title };

    let pr = client.post(
        &client.repo_path("pulls"),
        json!({
            "head": head_ref_name,
            "base": base_ref_name,
            "title": title,
            "body": body,
        }),
    )?;

    let number = pr["number"]
        .as_i64()
        .ok_or_else(|| user_error("Forgejo create pull request response missing 'number'"))?;
    let title = pr["title"].as_str().unwrap_or_default();
    println!("Created pull request #{number} ({title})");

    Ok(())
}

fn update_pr(
    client: &ForgejoClient,
    commit: &Commit,
    existing_pr: &ExistingPr,
    base_ref_name: &str,
    message: Option<&str>,
) -> Result<(), CommandError> {
    let (title, body) = split_title_body(commit.description());
    // Don't accidentally take a pull request out of draft state.
    let title = if existing_pr.draft {
        wip_title(&title)
    } else {
        title
    };

    let mut changes = serde_json::Map::new();
    if base_ref_name != existing_pr.base_ref_name {
        changes.insert("base".to_string(), Value::String(base_ref_name.to_string()));
    }
    if title != existing_pr.title {
        changes.insert("title".to_string(), Value::String(title.clone()));
    }
    if body != existing_pr.body {
        changes.insert("body".to_string(), Value::String(body.clone()));
    }

    if changes.is_empty() {
        println!(
            "No changes needed for PR #{} ({})",
            existing_pr.number, title
        );
    } else {
        let pr = client.patch(
            &client.repo_path(&format!("pulls/{}", existing_pr.number)),
            Value::Object(changes),
        )?;
        let number = pr["number"]
            .as_i64()
            .ok_or_else(|| user_error("Forgejo edit pull request response missing 'number'"))?;
        let title = pr["title"].as_str().unwrap_or_default();
        println!("Updated PR #{number} ({title})");
    }

    if let Some(message) = message {
        client.post(
            &client.repo_path(&format!("issues/{}/comments", existing_pr.number)),
            json!({ "body": message }),
        )?;
    }

    Ok(())
}

fn split_title_body(description: &str) -> (String, String) {
    if let Some((title, body)) = description.split_once('\n') {
        (title.to_string(), body.to_string())
    } else {
        (description.to_string(), String::new())
    }
}
