// Copyright 2026 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use serde_json::json;

use crate::cli_util::CommandHelper;
use crate::cli_util::RevisionArg;
use crate::command_error::CommandError;
use crate::command_error::user_error;
use crate::command_error::user_error_with_message;
use crate::commands::cr::CrRebaseArgs;
use crate::commands::cr::rebase::execute_rebase_plans;
use crate::commands::cr::rebase::rebase_target_revset;
use crate::commands::cr::rebase::resolve_rebase_roots;
use crate::commands::github::client::GitHubClient;
use crate::ui::Ui;
use jj_lib::backend::CommitId;
use jj_lib::ref_name::RemoteName;
use jj_lib::repo::Repo as _;
use jj_lib::rewrite::EmptyBehavior;

pub async fn cmd_github_rebase(
    ui: &mut Ui,
    command: &CommandHelper,
    remote_name: &RemoteName,
    args: &CrRebaseArgs,
) -> Result<(), CommandError> {
    let client = GitHubClient::new(ui, command, remote_name.as_str()).await?;

    let target_revset = rebase_target_revset(args);
    let mut workspace_command = command.workspace_helper(ui).await?;
    let root_ids = resolve_rebase_roots(ui, &workspace_command, &target_revset).await?;
    writeln!(
        ui.status(),
        "Rebasing revset: {} ({})",
        target_revset,
        root_ids.len()
    )?;

    if root_ids.is_empty() {
        writeln!(ui.status(), "No revisions to rebase.")?;
        return Ok(());
    }

    let plans: Vec<(CommitId, CommitId)> = {
        let push_bookmark_template_text = workspace_command
            .settings()
            .get_string("templates.git_push_bookmark")?;
        let push_bookmark_template =
            workspace_command.parse_commit_template(ui, &push_bookmark_template_text)?;

        let mut plans: Vec<(CommitId, CommitId)> = Vec::new();
        for root_id in &root_ids {
            let root_commit = workspace_command
                .repo()
                .store()
                .get_commit_async(root_id)
                .await?;
            let push_bookmark = String::from_utf8(
                push_bookmark_template.format_plain_text(&root_commit),
            )
            .map_err(|err| {
                user_error_with_message(
                    "Invalid character in bookmark name generated by templates.git_push_bookmark",
                    err.utf8_error(),
                )
            })?;
            if push_bookmark.is_empty() {
                return Err(user_error(
                    "Empty bookmark name generated by templates.git_push_bookmark",
                ));
            }

            let merge_target = find_pr_base_for_root(&client, &push_bookmark)?;

            let base_revset = if let Some(merge_target) = merge_target {
                let base = format!("{}@{}", merge_target, remote_name.as_symbol());
                writeln!(
                    ui.status(),
                    "Found PR merge target '{}' for {:.12}, rebasing descendants onto {}",
                    merge_target,
                    root_commit.change_id(),
                    base
                )?;
                base
            } else if args.all_prs {
                writeln!(
                    ui.status(),
                    "No PR found for descendants of {:.12}, skipping",
                    root_commit.change_id()
                )?;
                continue;
            } else {
                let base = format!(
                    "{}@{}",
                    client.default_merge_target,
                    remote_name.as_symbol()
                );
                writeln!(
                    ui.status(),
                    "No PR found for descendants of {:.12}, rebasing onto default target {}",
                    root_commit.change_id(),
                    base
                )?;
                base
            };

            writeln!(
                ui.status(),
                "Rebasing {:.12} onto {}",
                root_commit.change_id(),
                base_revset
            )?;

            let base_commit = workspace_command
                .resolve_single_rev(ui, &RevisionArg::from(base_revset))
                .await?;
            plans.push((root_id.clone(), base_commit.id().clone()));
        }

        plans
    };

    if plans.is_empty() {
        writeln!(ui.status(), "No revisions selected for rebasing.")?;
        return Ok(());
    }

    execute_rebase_plans(
        ui,
        &mut workspace_command,
        &plans,
        EmptyBehavior::AbandonNewlyEmpty,
        format!("rebase {} commit(s) and their descendants", plans.len()),
    )
    .await
}

fn find_pr_base_for_root(
    client: &GitHubClient,
    head_ref_name: &str,
) -> Result<Option<String>, CommandError> {
    let data = client.graphql(
        r#"
            query PullRequestBaseRefs($owner: String!, $name: String!, $headRefName: String!) {
                repository(owner: $owner, name: $name) {
                    pullRequests(headRefName: $headRefName, first: 1) {
                        nodes { baseRefName }
                    }
                }
            }
        "#,
        json!({
            "owner": client.repo_owner,
            "name": client.repo_name,
            "headRefName": head_ref_name,
        }),
    )?;
    Ok(data["repository"]["pullRequests"]["nodes"]
        .as_array()
        .and_then(|prs| prs.first())
        .and_then(|pr| pr["baseRefName"].as_str())
        .map(ToOwned::to_owned))
}
