// Copyright 2026 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use futures::TryStreamExt as _;
use reqwest::StatusCode;
use serde_json::Value;
use serde_json::json;
use std::collections::HashMap;
use std::collections::HashSet;

use crate::cli_util::CommandHelper;
use crate::cli_util::RevisionArg;
use crate::command_error::CommandError;
use crate::command_error::user_error;
use crate::command_error::user_error_with_message;
use crate::commands::cr::CrUploadArgs;
use crate::commands::git::cmd_git_push_changes;
use crate::commands::github::client::GitHubClient;
use crate::ui::Ui;
use jj_lib::backend::CommitId;
use jj_lib::commit::Commit;
use jj_lib::object_id::ObjectId as _;
use jj_lib::ref_name::RemoteName;
use jj_lib::repo::Repo as _;

pub async fn cmd_github_upload(
    ui: &mut Ui,
    command: &CommandHelper,
    remote_name: &RemoteName,
    args: &CrUploadArgs,
) -> Result<(), CommandError> {
    let client = GitHubClient::new(ui, command, remote_name.as_str()).await?;
    let workspace_command = command.workspace_helper(ui).await?;

    let selected_revset = args.revision.clone();
    let commit_ids: Vec<CommitId> = workspace_command
        .resolve_some_revsets(ui, &[RevisionArg::from(selected_revset)])
        .await?
        .into_iter()
        .rev()
        .collect();
    workspace_command.check_rewritable(&commit_ids).await?;

    let push_bookmark_template_text = workspace_command
        .settings()
        .get_string("templates.git_push_bookmark")?;
    let push_bookmark_template =
        workspace_command.parse_commit_template(ui, &push_bookmark_template_text)?;

    let commits: Vec<Commit> = {
        let mut out = Vec::with_capacity(commit_ids.len());
        for id in &commit_ids {
            out.push(
                workspace_command
                    .repo()
                    .store()
                    .get_commit_async(id)
                    .await?,
            );
        }
        out
    };

    let mut commit_to_push_bookmark: HashMap<CommitId, String> = HashMap::new();
    for commit in &commits {
        let push_bookmark = String::from_utf8(push_bookmark_template.format_plain_text(commit))
            .map_err(|err| {
                user_error_with_message(
                    "Invalid character in bookmark name generated by templates.git_push_bookmark",
                    err.utf8_error(),
                )
            })?;
        if push_bookmark.is_empty() {
            return Err(user_error(
                "Empty bookmark name generated by templates.git_push_bookmark",
            ));
        }
        commit_to_push_bookmark.insert(commit.id().clone(), push_bookmark);
    }

    // Create/update push bookmarks and push all selected changes.
    let change_revisions = commits
        .iter()
        .map(|commit| RevisionArg::from(commit.id().hex().clone()))
        .collect();
    cmd_git_push_changes(ui, command, remote_name, change_revisions).await?;

    // Gather existing PRs and stack numbers before mutating.
    let mut existing_pr_by_commit: HashMap<CommitId, ExistingPr> = HashMap::new();
    let mut existing_stack_numbers: HashSet<i64> = HashSet::new();
    for commit in &commits {
        let head_ref_name = commit_to_push_bookmark
            .get(commit.id())
            .expect("bookmark mapped for every selected commit");
        if let Some(existing_pr) = get_pr_by_head_ref(&client, head_ref_name)? {
            if let Some(stack_number) = existing_pr.stack_number {
                existing_stack_numbers.insert(stack_number);
            }
            existing_pr_by_commit.insert(commit.id().clone(), existing_pr);
        }
    }

    // Existing stacks are append-only; unstack and recreate as in Python port.
    for stack_number in existing_stack_numbers {
        unstack_pull_request_stack(&client, stack_number)?;
    }

    let mut new_stack: Vec<i64> = Vec::new();
    for commit in &commits {
        let head_ref_name = commit_to_push_bookmark
            .get(commit.id())
            .expect("bookmark mapped for every selected commit");
        let base_ref_name = compute_base_ref_name(
            ui,
            &workspace_command,
            &commit_to_push_bookmark,
            commit,
            &client.default_merge_target,
        )
        .await?;

        let pr = if let Some(existing_pr) = existing_pr_by_commit.get(commit.id()) {
            update_pr(
                &client,
                commit,
                existing_pr,
                &base_ref_name,
                args.message.as_deref(),
            )?
        } else {
            create_pr(&client, commit, head_ref_name, &base_ref_name, args.draft)?
        };
        new_stack.push(pr.number);
    }

    if new_stack.len() > 1 {
        create_pull_request_stack(&client, &new_stack)?;
    }

    Ok(())
}

#[derive(Clone, Debug)]
struct ExistingPr {
    id: String,
    number: i64,
    title: String,
    body: String,
    base_ref_name: String,
    stack_number: Option<i64>,
}

#[derive(Clone, Debug)]
struct UploadPr {
    number: i64,
}

async fn compute_base_ref_name(
    ui: &Ui,
    workspace_command: &crate::cli_util::WorkspaceCommandHelper,
    commit_to_push_bookmark: &HashMap<CommitId, String>,
    commit: &Commit,
    default_merge_target: &str,
) -> Result<String, CommandError> {
    let Some(first_parent_id) = commit.parent_ids().first() else {
        return Ok(default_merge_target.to_string());
    };
    if is_immutable_commit(ui, workspace_command, first_parent_id).await? {
        Ok(default_merge_target.to_string())
    } else if let Some(push_bookmark) = commit_to_push_bookmark.get(first_parent_id) {
        Ok(push_bookmark.clone())
    } else {
        let parent_commit = workspace_command
            .repo()
            .store()
            .get_commit_async(first_parent_id)
            .await?;
        let template_text = workspace_command
            .settings()
            .get_string("templates.git_push_bookmark")?;
        let template = workspace_command.parse_commit_template(ui, &template_text)?;
        let push_bookmark =
            String::from_utf8(template.format_plain_text(&parent_commit)).map_err(|err| {
                user_error_with_message(
                    "Invalid character in bookmark name generated by templates.git_push_bookmark",
                    err.utf8_error(),
                )
            })?;
        if push_bookmark.is_empty() {
            return Err(user_error(
                "Empty bookmark name generated by templates.git_push_bookmark",
            ));
        }
        Ok(push_bookmark)
    }
}

async fn is_immutable_commit(
    ui: &Ui,
    workspace_command: &crate::cli_util::WorkspaceCommandHelper,
    commit_id: &CommitId,
) -> Result<bool, CommandError> {
    let expr = workspace_command.parse_revset(
        ui,
        &RevisionArg::from(format!("{} & immutable()", commit_id.hex())),
    )?;
    let mut stream = expr.evaluate_to_commit_ids()?;
    Ok(stream.try_next().await?.is_some())
}

fn get_pr_by_head_ref(
    client: &GitHubClient,
    head_ref_name: &str,
) -> Result<Option<ExistingPr>, CommandError> {
    let data = client.graphql(
        r#"
            query GetPullRequestByHeadRef($owner: String!, $name: String!, $headRef: String!, $states: [PullRequestState!]) {
                repository(owner: $owner, name: $name) {
                    pullRequests(headRefName: $headRef, states: $states, first: 1) {
                        nodes {
                            id
                            number
                            title
                            body
                            stack {
                                number
                            }
                            baseRefName
                        }
                    }
                }
            }
        "#,
        json!({
            "owner": client.repo_owner,
            "name": client.repo_name,
            "headRef": head_ref_name,
            "states": ["OPEN"],
        }),
    )?;

    let Some(pr_value) = data["repository"]["pullRequests"]["nodes"]
        .as_array()
        .and_then(|prs| prs.first())
    else {
        return Ok(None);
    };

    parse_existing_pr(pr_value).map(Some)
}

fn parse_existing_pr(pr: &Value) -> Result<ExistingPr, CommandError> {
    let id = pr["id"]
        .as_str()
        .ok_or_else(|| user_error("GitHub PR is missing id"))?
        .to_string();
    let number = pr["number"]
        .as_i64()
        .ok_or_else(|| user_error("GitHub PR is missing number"))?;
    let title = pr["title"].as_str().unwrap_or_default().to_string();
    let body = pr["body"].as_str().unwrap_or_default().to_string();
    let base_ref_name = pr["baseRefName"].as_str().unwrap_or_default().to_string();
    let stack_number = pr["stack"]["number"].as_i64();

    Ok(ExistingPr {
        id,
        number,
        title,
        body,
        base_ref_name,
        stack_number,
    })
}

fn create_pr(
    client: &GitHubClient,
    commit: &Commit,
    head_ref_name: &str,
    base_ref_name: &str,
    draft: bool,
) -> Result<UploadPr, CommandError> {
    let (title, body) = split_title_body(commit.description());

    let data = client.graphql(
        r#"
            mutation CreatePullRequest($input: CreatePullRequestInput!) {
                createPullRequest(input: $input) {
                    pullRequest {
                        number
                        title
                    }
                }
            }
        "#,
        json!({
            "input": {
                "repositoryId": client.repo_id,
                "headRefName": head_ref_name,
                "baseRefName": base_ref_name,
                "title": title,
                "body": body,
                "draft": draft,
            }
        }),
    )?;

    let pr = &data["createPullRequest"]["pullRequest"];
    let number = pr["number"]
        .as_i64()
        .ok_or_else(|| user_error("GitHub createPullRequest response missing number"))?;
    let title = pr["title"].as_str().unwrap_or_default().to_string();
    println!("Created pull request #{number} ({title})");

    Ok(UploadPr { number })
}

fn update_pr(
    client: &GitHubClient,
    commit: &Commit,
    existing_pr: &ExistingPr,
    base_ref_name: &str,
    _message: Option<&str>,
) -> Result<UploadPr, CommandError> {
    let (title, body) = split_title_body(commit.description());

    let mut changes = serde_json::Map::new();
    if base_ref_name != existing_pr.base_ref_name {
        changes.insert(
            "baseRefName".to_string(),
            Value::String(base_ref_name.to_string()),
        );
    }
    if title != existing_pr.title {
        changes.insert("title".to_string(), Value::String(title.clone()));
    }
    if body != existing_pr.body {
        changes.insert("body".to_string(), Value::String(body.clone()));
    }

    if changes.is_empty() {
        println!(
            "No changes needed for PR #{} ({})",
            existing_pr.number, title
        );
        return Ok(UploadPr {
            number: existing_pr.number,
        });
    }

    let mut input = serde_json::Map::new();
    input.insert(
        "pullRequestId".to_string(),
        Value::String(existing_pr.id.clone()),
    );
    input.extend(changes);

    let data = client.graphql(
        r#"
            mutation UpdatePullRequest($input: UpdatePullRequestInput!) {
                updatePullRequest(input: $input) {
                    pullRequest {
                        number
                        title
                    }
                }
            }
        "#,
        json!({ "input": input }),
    )?;
    let pr = &data["updatePullRequest"]["pullRequest"];
    let number = pr["number"]
        .as_i64()
        .ok_or_else(|| user_error("GitHub updatePullRequest response missing number"))?;
    let title = pr["title"].as_str().unwrap_or_default().to_string();
    println!("Updated PR #{number} ({title})");

    // TODO: if commit content changed and _message is set, add it as a comment.

    Ok(UploadPr { number })
}

fn create_pull_request_stack(
    client: &GitHubClient,
    pull_requests: &[i64],
) -> Result<i64, CommandError> {
    let path = format!("/repos/{}/{}/stacks", client.repo_owner, client.repo_name);
    let (_, data) = client.rest_post(&path, Some(json!({ "pull_requests": pull_requests })))?;

    data["number"]
        .as_i64()
        .ok_or_else(|| user_error("GitHub create stack response missing number"))
}

fn unstack_pull_request_stack(
    client: &GitHubClient,
    stack_number: i64,
) -> Result<(), CommandError> {
    let path = format!(
        "/repos/{}/{}/stacks/{stack_number}/unstack",
        client.repo_owner, client.repo_name
    );
    let (status, data) = client.rest_post(&path, None)?;

    match status {
        StatusCode::NO_CONTENT => Ok(()),
        StatusCode::OK => {
            let remaining = data["pull_requests"].as_array().map_or(0, |prs| prs.len());
            Err(user_error(format!(
                "Stack #{stack_number} could not be fully unstacked; {remaining} pull request(s) remain on the stack"
            )))
        }
        _ => Err(user_error(format!(
            "Unexpected status code while unstacking stack #{stack_number}: {status}"
        ))),
    }
}

fn split_title_body(description: &str) -> (String, String) {
    if let Some((title, body)) = description.split_once('\n') {
        (title.to_string(), body.to_string())
    } else {
        (description.to_string(), String::new())
    }
}
