# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: cargo-build
        name: cargo build
        description: Make sure the project builds before committing.
        entry: cargo build --workspace --all-targets
        language: system
        types: [rust]
        pass_filenames: false
